### PR TITLE
v68: privacy-ish fixes

### PR DESCRIPTION
**Pull request by laniakea64**
**Disable DiscoveryStream / "Recommended by Pocket"**

Waterfox already crippled this, but it was still active.  Disabling it reduces browser console noise and cleans up the new tab page.

**Disable urlbar speculative connect by default**

`browser.urlbar.speculativeConnect.enabled` when set to `true` causes Waterfox to make weird connections that are difficult to track down.  Standard troubleshooting an affected profile erroneously points to `places.sqlite` as the cause, which results in a wild goose chase.  This should not be enabled unless the user explicitly wants it and knows about it.

**Expose media.gmp-manager.updateEnabled in about:config by default**

Same patch as https://github.com/MrAlex94/Waterfox/pull/478

### CODE REVIEW

**Comment by laniakea64** [comment]
Hi @MrAlex94 do you need anything else from me in order to review and merge this?

**Comment by grahamperrin** [comment]
Is it possible to disable things without _locking_ preferences?

**Comment by laniakea64** [comment]
@grahamperrin Yes, that's exactly what this does for urlbar speculative connect.

**Comment by grahamperrin** [comment]
Well, yes, but I'm looking at what's locked ;-)

Consider e.g. #979

**Comment by laniakea64** [comment]
@grahamperrin That's different.  Top sites actually works fine when unlocked and enabled (and I do have a local patch to unlock that pref, and I currently have it flipped on in my daily-use profile).  And that locking was erroneous in the first place - https://github.com/MrAlex94/Waterfox/issues/979#issuecomment-500114917
(and it has been unlocked as I type this :smiley: )

The prefs locked by this PR control something that **doesn't** work and _intentionally_ doesn't work.

Why do you want to enable it?

**Comment by grahamperrin** [comment]
Pocket: because I'm an active user, I very often take a selection of recommendations.

**Comment by laniakea64** [comment]
Hmm, removal of Pocket is a [feature of Waterfox](https://github.com/MrAlex94/Waterfox#features) and "Recommended by Pocket" doesn't work in Waterfox.  And I've found "Recommended by Pocket" to be somewhat pushy in Firefox and not so easy to disable there.  So I would rather see this PR merged as-is.

Maybe you could raise a separate issue requesting to add a mozconfig option to enable Pocket and "Recommended by Pocket" at build time?  Such mozconfig option would mean these prefs would be locked to `false` in normal Waterfox builds, but unlocked in Pocket-enabled builds, and this way Pocket stuff would still not be forced on users who don't want it.

**Comment by MrAlex94** [comment]
All looked good to me. Sorry had received this just as I set off traveling!

**Pull request merged**
