### PR TITLE
[G3] Add restart menu item, status bar, tab controls and menu style

### PR DESCRIPTION
**Pull request by hawkeye116477**
On Linux works fine, so testing left for other OSes.

On Mac OS probably should be tested when title bar is disabled and tab par position is different than default.  In that time maximize, close and minimize buttons should be on `#toolbar-menubar-pagetitle` (top bar).

I looked at https://github.com/MrAlex94/Waterfox/commit/3feb30bb0d703af094c85fb2f27a3e78f6fa8a89#diff-05ebdcf6166c58311fdc8918b6de3cf298a5b53ee0c51df85b5d1f7ad2148b8a and all should be applied instantly now.

Anyway, it's not all, Current had some more settings added by me, so maybe I'll look into that later too.

### CODE REVIEW

**Comment by MrAlex94** [comment]
Thanks for this. Seem to be having issues with about:preferences#general loading:

```
Uncaught (in promise) TypeError: WeakMap key must be an object, got aElement
    addSyncFromPrefListener chrome://global/content/preferencesBindings.js:304
    init chrome://browser/content/preferences/main.js:823
    init chrome://browser/content/preferences/preferences.js:69
    initializeCategories chrome://browser/content/preferences/findInPage.js:93
    init chrome://browser/content/preferences/findInPage.js:49
    requestIdleCallback handler*init chrome://browser/content/preferences/findInPage.js:49
    init_all chrome://browser/content/preferences/preferences.js:94
    EventListener.handleEvent* chrome://browser/content/preferences/preferences.js:75
preferencesBindings.js:304:35
    initializeCategories chrome://browser/content/preferences/findInPage.js:91
    AsyncFunctionThrow self-hosted:697
    (Async: async)
    init chrome://browser/content/preferences/findInPage.js:49
    (Async: requestIdleCallback handler)
    init chrome://browser/content/preferences/findInPage.js:49
    init_all chrome://browser/content/preferences/preferences.js:94
    (Async: EventListener.handleEvent)
    <anonymous> chrome://browser/content/preferences/preferences.js:75
```

**Comment by hawkeye116477** [comment]
@MrAlex94 I'm assuming that you checked that on other OS than Linux. Windows Controls Position preferences are currently only marked for Linux, but in main.js there is code for assigning listener to `windowControlsRadioGroup`, which is only available on Linux, so error appears. Anyway, that should be fixed in my latest commit.

**Comment by MrAlex94** [comment]
Thanks! Will test and merge if all okay 👍

**Comment by MrAlex94** [comment]
Works well! Awesome. The issue I had was that the Windows window controls were vertical instead of horizontal, but seems to be okay now!

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
It seems that problem with disappearing title bar from Current in macOS (and address bar glitch when using standard Firefox theme) is still present.

Screen Shot 2020-12-28 at 3 48 45

**Pull request merged**
