### PR TITLE
(WF68) Enable containers by default.

### PR DESCRIPTION
**Pull request by Peacock365**
See header.

### CODE REVIEW

**Comment by laniakea64** [comment]
This also needs `privacy.userContext.longPressBehavior` set to `2`

**Comment by Ibuprophen** [comment]
@Peacock365, I did see what @laniakea64 may have been referring to... 

`Line 1643` refers to `privacy.userContext.longPressBehavior`being set to `2`but, `Line 1649` reflects `0`.


~Ibuprophen

**Comment by grahamperrin** [comment]
https://blog.mozilla.org/tanvi/2017/10/03/update-firefox-containers/#comment-36309

Need to check the (Mozilla) rationale for continuing to not enable these features by default. IIRC there was an overriding wish to promote extensions-based control of the preferences but a long time has passed since then …

**Comment by laniakea64** [comment]
> Need to check the (Mozilla) rationale for continuing to not enable these features by default. 

I looked into this a while ago, and IIRC it boiled down to, they put more features in their Multi-Account Containers extension and prefer people use that.  See e.g. at the bottom of https://support.mozilla.org/en-US/kb/containers

Edit: And also from the [description of Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/):
> Firefox Multi-Account Containers was first introduced as "Containers" available only in Firefox Nightly. It went on to be a Test Pilot Experiment, where we improved the user experience and added new features. Now it exists here as an extension that can be installed by all Firefox users.
> 
> Although you can still use the feature built into Firefox Nightly, we recommend using this extension as it has a richer user experience.

**Pull request closed without merging**
