### PR TITLE
Readded time and progress bar code from downloads toolbar icon

### PR DESCRIPTION
**Pull request by hockeymikey**
The old downloads icon was removed in v55 after being phased out and disabled in v54(?).  Users still have to use some css to regain the old look like in v54.
Changes found from: https://reviewboard.mozilla.org/r/136252/
I did not test this build.

### CODE REVIEW

**Comment by MrAlex94** [comment]
Really sorry for the delay. I'll look into adding this to the next release.

**Comment by hockeymikey** [comment]
No worries.  Glad to hear!

**Comment by hook321** [comment]
@hockeymikey Will this still be possible to do when Waterfox is based on Quantum?

**Comment by grahamperrin** [comment]
Cross references: 

- https://redd.it/7p1pd4 (archived)
- https://redd.it/a6tnnp

**Comment by hockeymikey** [comment]
> @hockeymikey Will this still be possible to do when Waterfox is based on Quantum?

Probably?  I don't know, this was a year ago. Never knew Waterfox was going to Quantum. Better not screw up CTR or any of that (but I digress).

**Pull request closed without merging**
