### PR TITLE
Update Japanese localize

### PR DESCRIPTION
**Pull request by Ryosuke-Asano**
Continuing from the last issue, we have enhanced the Japanese localization.

Localization has also been applied to ```~\Waterfox\browser\extensions\extensibles\locales```.

Several mistranslations have also been reduced and tracked to the latest version in English.

### CODE REVIEW

**Comment by Ryosuke-Asano** [comment]
Referring to other pull requests, it looks like it will be after https://github.com/WaterfoxCo/Waterfox/pull/2662.

If there is anything else you would like me to do, feel free.

However, I am a student developing other Firefox derivatives, so I will only respond when I have free time. Sorry.

**Comment by adamp01** [comment]
Thanks @surapunoyousei - we will get this merged along with other l10n work shortly. 

For reference, we will be using this platform to track translations moving forward (do not worry about copying your current work into the platform, I can do that at some point). - https://waterfox.crowdin.com/browser-l10n

**Comment by Ryosuke-Asano** [comment]
> Thanks @surapunoyousei - we will get this merged along with other l10n work shortly.
> 
> For reference, we will be using this platform to track translations moving forward (do not worry about copying your current work into the platform, I can do that at some point). - https://waterfox.crowdin.com/browser-l10n

Will you be using <a href="https://waterfox.crowdin.com/browser-l10n">crowdin</a> for localization in the future?

Which is a good thing, because it makes it easier for me to contribute since I can do it in less time!

**Comment by adamp01** [comment]
Correct, all future translations should be done through Crowdin!

**Comment by MrAlex94** [comment]
Sorry for the delay!

This is now handled by Crowdin and will be live in G5 Beta 2. 

435bd9a2683e09600655dc322098650479a51a5a

**Pull request closed without merging**
