### PR TITLE
Classic vs Current

### PR DESCRIPTION
**Pull request by topnotchaero**
Will the current version support legacy add-ons?  Thank you

### CODE REVIEW

**Comment by hawkeye116477** [comment]
Why you created PR for question? You should rather open issue.

**Comment by topnotchaero** [comment]
I’m not familiar with the process.  Sorry.

**Comment by hawkeye116477** [comment]
https://github.com/MrAlex94/Waterfox/issues

**Comment by hawkeye116477** [comment]
You can also ask that on reddit => https://www.reddit.com/r/waterfox/, which is better place rather.

**Pull request closed without merging**
