### PR TITLE
Add GtkFileChooserNative support, new js properties and other improvements to Waterfox Classic

### PR DESCRIPTION
**Pull request by hawkeye116477**
Borrowed from https://github.com/MoonchildProductions/UXP/commit/47c48dfcb87a574f6b96f3abf3ed14b9b08b2371.
This adds support for native KDE dialog.
But to make it really working, users needs to have `xdg-desktop-portal-kde` package and run Waterfox with `GTK_USE_DIALOG=1`.
That package is available from Ubuntu 18 and Debian 10. But on GTK lower than 3.24.4 can be some problems (Ubuntu 18), so in that case SUSE's solution which I use on my package still will be better (even it works on Ubuntu 16 and Debian 9).

### CODE REVIEW

**Comment by grahamperrin** [comment]
Thanks! 

<strike>https://lists.freebsd.org/pipermail/freebsd-current/2019-September/074405.html</strike>

https://lists.freebsd.org/pipermail/freebsd-current/2019-September/074442.html

> … dbus portal …

**Comment by hawkeye116477** [comment]
Additionally:
* Added new js properties => `Symbol​.prototype​.description, String.prototype.trim{Start,End}`.
* Fix for emoji (#919). Still some emojis are not colored, but now it's better, they look like same as on newest Firefox/Waterfox Current and is possible to change font for emojis.
* Experimental support for AV1 in MP4 container (#897, disabled by default, can be enabled by setting media.av1.enabled to true in about:config, also to make it working needed is adding `ac_add_options --enable-av1` to mozconfig). I added similar things which are on UXP, so may be same problems as on https://github.com/MoonchildProductions/UXP/issues/888.
* Small fixes for MP4 parser.
* Added the path to the running binary to about:support. 
* Added new strings for language packs (#903 and CSP things which I added previously, only Polish language is translated, other are in English).
* Fixes for WebP (some changes borrowed from UXP/Basilisk)

I also created repository with unpacked language packs for easier collaboration => `https://github.com/hawkeye116477/LanguagePacksForWaterfox` :smile:. I think that repository should be created by @MrAlex94, Cyberfox and Pale Moon also has similar.

Update: I added also some other useful fixes.

**Comment by MrAlex94** [comment]
Thanks. I'm going to change the way language packs are handled, and do it at the packing stage instead. Will go through these all, cheers for the commits!

**Comment by hawkeye116477** [comment]
@MrAlex94 Ok. I added also fixes for #612 and #1065 now. You can merge, all I tested and seems that everything works as intended :smile:

Update: I also added fix for #1079 (only problem with Nintendo mentioned on Reddit not solved).

**Review by Ibuprophen — COMMENTED** [review]
Looks Very Good!

Kudos to You @hawkeye116477!!! :-) 


~Ibuprophen

**Comment by hawkeye116477** [comment]
I added some mp4 crash fixes and fix for `mediamarkt.de` (https://www.reddit.com/r/waterfox/comments/c38byn/page_layout_problem/) now.

**Comment by grahamperrin** [comment]
☝ thumbs up for sheer effort! (I haven't tested, but don't doubt the goodness of all of this …)

**Comment by hawkeye116477** [comment]
Now added fix for #1066 and https://www.reddit.com/r/waterfox/comments/d62qit/mlbcom_banner_rendering_issues/.

@MrAlex94 Do I need to do something to green light this :smile:? And don't worry, I left Nintendo's site for you (Shadow DOM v1) and maybe `https://bugzilla.mozilla.org/show_bug.cgi?id=1392177`.

Updated: Added fix for #1004 also.

**Comment by MrAlex94** [comment]
> @MrAlex94 Do I need to do something to green light this 😄? And don't worry, I left Nintendo's site for you (Shadow DOM v1) and maybe `https://bugzilla.mozilla.org/show_bug.cgi?id=1392177`.

Not at all! Just testing the features that have been affected by the changes on all the platforms, just in case there's a breakage somewhere. Has happened to me so many times before when I merge changes from upstream, trying to be a bit careful this time so I don't ruin things for everyone 😅. Sorry it's taking so long, literally testing as we speak, VMs are slow!

**Comment by hawkeye116477** [comment]
Ok, all in all right, if you're in a hurry, the devil is happy.

**Comment by MrAlex94** [comment]
Excellent job! All worked perfectly.

**Pull request merged**
