### PR TITLE
v68: fixes for the Australis-Photon themes

### PR DESCRIPTION
**Pull request by laniakea64**
**Get the Australis-Photon themes working as intended and fix consistency issues**

Fixes https://github.com/MrAlex94/Waterfox/issues/1090

Apparently Waterfox had already added several distinct Australis-Photon styles, one for each built-in theme, but only the dark Australis-Photon style was ever getting applied.  This patch introduces selecting the correct Australis-Photon style for the selected built-in theme, and fixes the consistency issues applying it.  Seems to work well as long as the user does not manually mess with `extensions.activeThemeID`.  Given how it was implemented before this patch, I assume that edge case is not a concern.

Note: Seeing the lack of an `else` clause in the existing implementation, I assumed the design intent was to not apply any Australis-Photon style when a persona is in use.

**Add a pref to disable the Australis-Photon themes**

See https://github.com/MrAlex94/Waterfox/issues/1131 for context.

### CODE REVIEW

**Comment by laniakea64** [comment]
Hi @MrAlex94 did I correctly understand the intent?
Do you need anything else from me on this in order to review and merge?

**Comment by devarped** [comment]
I've built Waterfox with that commitand I can see that tabls use colors from Light theme on Default theme, which in my opinion does not look great.
tabs

**Comment by laniakea64** [comment]
> I've built Waterfox with that commit and I can see that tabls use colors from Light theme on Default theme, 

Good catch, I didn't notice that `australis-default.css` was just a copy of `australis-light.css`!  This is not right, it means the Australis-Photon Default theme will make unreadable white-text-on-white-tabs for users with dark system theme (and I have confirmed this with Adwaita-Dark GTK theme).

I was able to fix `australis-default.css` to make active tab color based on system theme so it doesn't create unreadable text, but I'm not sure this fix is suitable for a PR, since with some GTK themes it makes the active tab not so easy to distinguish from the tab-bar background.  It would also need to be tested on Windows and Mac OS, which I'm not able to do.

If you'd like to take a look and experiment with it, I pushed it to https://github.com/laniakea64/Waterfox/tree/v68-theme-fix-2

**Comment by devarped** [comment]
>I'm not sure this fix is suitable for a PR, since with some GTK themes it makes the active tab not so easy to distinguish from the tab-bar background.

Maybe add some kind of thin border to the active tab? It will definely change previous style of tabs, but I don't think it will look too bad.

**Comment by laniakea64** [comment]
> Maybe add some kind of thin border to the active tab? It will definely change previous style of tabs, but I don't think it will look too bad.

That's how Waterfox 56 default theme solves this, see e.g. screenshots in https://github.com/MrAlex94/Waterfox/issues/459#issuecomment-370201445

Unfortunately I don't know enough about SVG to know how to add the borders, sorry.

**Comment by laniakea64** [comment]
The Australis-Photon themes are overriding people's userChrome.css, and this patch is going to make that breakage even more prevalent, see https://github.com/MrAlex94/Waterfox/issues/1131#issuecomment-530021496

@grahamperrin suggested that the adding a `about:config` pref to disable the Australis-Photon themes would be the best solution for that issue - https://github.com/MrAlex94/Waterfox/issues/1131#issuecomment-530068924
I would like to add such patch to this PR before merge.  (I will keep the Australis-Photon themes enabled by default.)

**Comment by laniakea64** [comment]
> I would like to add such patch to this PR before merge. (I will keep the Australis-Photon themes enabled by default.)

Done.

Note to testers: this seems to require once starting Waterfox with `-purgecaches` command-line switch.

**Comment by MrAlex94** [comment]
Okay so my plan is to have a separate and default Australis-Photon theme, and keep the other defaults as well for those who want to use custom CSS. That way, we keep the Waterfox look while letting people customise as they please. Sorry for not making this clearer. I'll leave this here for now and come back to review if anything changes.

**Comment by laniakea64** [comment]
Thanks @MrAlex94 for responding.

I'm not sure if I will be able to find more time to look into this, but in case I can:

So the files for Dark/Light themes are at https://github.com/MrAlex94/Waterfox/tree/gecko68/browser/themes/addons , but where are the equivalent files for Default theme?

**Comment by MrAlex94** [comment]
I believe it's spread throughout the https://github.com/MrAlex94/Waterfox/tree/gecko68/browser/themes directory, it's not packaged like the compact themes.

**Comment by grahamperrin** [comment]
Thanks folks and @MrAlex94 to further clarify, is the plan to have **a GUI to a preference** e.g. https://github.com/MrAlex94/Waterfox/pull/1112/commits/adc456d4f724098dca6260d904778fb63b5d0cd9?

**Comment by laniakea64** [comment]
@grahamperrin Seems clear to me, that the plan is to make it separate entries in Tools > Add-ons > Themes, with one of the Australis-Photon themes being default, and the option of straight Photon offered there in the same way Light and Dark themes are now.

**Pull request closed without merging**
