### PR TITLE
[Classic] Incremental Shadow Dom v1 merge.

### PR DESCRIPTION
**Pull request by hawkeye116477**
Continuation of work started for webcomponents in #1394.

### CODE REVIEW

**Comment by MrAlex94** [comment]
Wow, great work! Will do some thorough testing 👍

**Comment by hawkeye116477** [comment]
I added additional changes. Now more tests should pass for adopted callback.

**Comment by MrAlex94** [comment]
Okay sweet, still testing :-)

**Comment by MrAlex94** [comment]
So we've been testing this out but seem to be hitting build issues when building with `--enable-tests`. Do you know if there are any missing tests for the relevant commits here?

**Comment by hawkeye116477** [comment]
I don't know. I added commit with few fixes for tests, but unfortunately still something fails (python script?) `['ValueError: Expecting property name: line 332316 column 1 (char 7089004)\n']`.

There also great tests on https://w3c-test.org/shadow-dom/ and https://github.com/mdn/web-components-examples :smile:.

**Comment by MrAlex94** [comment]
Thanks, it could be I've been missing tests from years ago that are causing the issues. Almost done with testing though, everything seems to be working as expected!

**Pull request merged**
