### PR TITLE
Update resetProfile.dtd – differs from Firefox

### PR DESCRIPTION
**Pull request by grahamperrin**
Partially address: 

- #390 in particular, "…  it won’t remove extensions, but it may reset their preferences."
- #391
- #392

Further action may include: 

- documentation.

### CODE REVIEW

**Comment by grahamperrin** [comment]
Will this expanded `.dtd` require a separate change to the size of the dialogue box(es)? Or does resizing occur automatically? 

More generally: are the bullet points in this `.dtd` a true, reasonably comprehensive reflection of the current state of things? 

I mention "this version of Waterfox" with the assumption that future versions will take different approaches. Losing – [or preserving](https://github.com/MrAlex94/Waterfox/issues/392) – metadata from [a Waterfox-oriented add-ons service](https://github.com/MrAlex94/Waterfox/issues/303); and so on.  

Ideally: I'd like this help routine to be jargon-free. 

More realistically: expect some users to neither know, nor care about, the difference between an _add-on_ and an _extension_ (in the context of this routine) … so a little jargon may be appropriate.

**Comment by grahamperrin** [comment]
## Multi-process defaults

I forgot: 

- [e10s: multiprocess enabled with incompatible add-ons after refreshing waterfox 56.0.3 · Issue #380 …](https://github.com/MrAlex94/Waterfox/issues/380)
- <https://github.com/MrAlex94/Waterfox/issues/397#issuecomment-366545838>.

If the next release (or beta) will not fix #380 then we should: 

1. probably demote _can help_ to (less affirmative) _may help_ in `refreshProfile.dialog.description1`
2. add a bullet point, maybe a final `refreshProfile.dialog.items.label6`, 

> enable multi-process &brandShortName;, even if a extension is incompatible with multi-process. 

– or words to that effect.

**Comment by MrAlex94** [comment]
The changes you've made seem reasonable, but [resetProfile.xul](https://github.com/MrAlex94/Waterfox/blob/master/toolkit/content/resetProfile.xul) needs to reference the new definitions as well. The [CSS](https://github.com/MrAlex94/Waterfox/blob/master/toolkit/content/resetProfile.css) may need adapting as well, if the options are too long.
Not sure what to do about mentioning multi-process though 🤔.

**Comment by grahamperrin** [comment]
At a glance, we might have missed a third line before the indented points: 

2018-03-31 18 03 40 refresh waterfox

I'll aim to fix by making more changes to https://github.com/MrAlex94/Waterfox/pull/488

**Pull request merged**
