### PR TITLE
Extend JPEG XL detection/recognition (also AVIF a tiny bit)

### PR DESCRIPTION
**Pull request by goodusername123**
Adds JPEG XL recognition to a few missing spots, Should hopefully fix issue #2962 however I can't test myself since I don't have a setup to compile Waterfox builds of my own.

### CODE REVIEW

**Comment by MrAlex94** [comment]
Thanks for submitting. Will take a look and revert.

**Comment by goodusername123** [comment]
@MrAlex94 
After doing another pass over the codebase I have come to realize there are quite a few spots that I have missed, Would it be fine if I attached another commit to this pull request with the extra places I originally missed? or would you prefer a separate pull request? The commit would be larger then the other ones currently present and would also include adding JXL as a supported file association type under Windows, along with some minor spots where AVIF recognition is also missing.

**Comment by MrAlex94** [comment]
You can push it here, no problem. I typically squash down commits to keep it manageable for rebasing on top of gecko-dev

**Comment by MrAlex94** [comment]
Thanks for the updated commits. Will revert ASAP.

**Pull request merged**
