### PR TITLE
Publish to Windows Package Managar (WinGet)

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

Before merging this:
1. Please add a GitHub token with `public_repo` scope as a repository secret and rename the secret name in the workflow.
2. Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @waterfoxco

The token in release.yml is changed because GitHub Action does not trigger WinGet workflow if the release is published by GitHub Action Bot.

### CODE REVIEW

**Comment by vedantmgoyal9** [comment]
@MrAlex94 @adamp01 does anyone have time to look into my pull request? It has been 2 months but there hasn't been any response from any of the maintainers.

**Comment by MrAlex94** [comment]
Sorry for the delayed response! I did a big rework of the workflows, with the idea of making package manager uploads easier.

I will be honest that I am hesitant to use an action that isn’t well used and/or slightly obfuscated (seems your action only has the dist output in the repo). Supply chain attacks are more common nowadays, but I will take a look and potentially use Microsoft’s native tools.

**Comment by vedantmgoyal9** [comment]
I think you were looking for source code which is present in the root of the project https://github.com/vedantmgoyal2009/winget-releaser/blob/main/main.ts and not in an src directory separately.

The action is relatively new, and hence the number of people, who are using the action, is not very large.

Gradually, when they'll become aware of there's some action that makes publishing to WinGet easier, they might want to use it but till then I'm manually creating PRs to add the action to the repos so that the latest release of the software is available in WinGet as soon as it is released. 

Also, many developers don't know about WinGet, or they prefer chocolatey over WinGet, or they don't want to take the burden of publishing their software to various package managers, therefore it is also one of the reasons that it seems the action is used by very few number of people.

**Comment by vedantmgoyal2009** [comment]
@MrAlex94 hello?

**Comment by vedantmgoyal2009** [comment]
@MrAlex94 hello?

**Comment by vedantmgoyal9** [comment]
@MrAlex94 Should I update the PR to switch to one of the Microsoft tools?

**Comment by MrAlex94** [comment]
Sorry for the delay - if you could get this patch to not use any external actions, I'd be happy to merge.

**Comment by MrAlex94** [comment]
This has been superseded by the community doing it, but will look into making it automated.

**Comment by vedantmgoyal9** [comment]
@mralex94 can you please re-open? it got missed from my todo-list somehow, but your closing of pr triggered a notification. Will update it to use microsoft wingetcreate, as soon as possible.

**Pull request closed without merging**
