### PR TITLE
[Current] Add another improvements and fixes (part 2)

### PR DESCRIPTION
**Pull request by hawkeye116477**
I noticed some problems when changing Tab Bar position, so here are fixes (only tested on Linux).

Now titlebar buttons should stay on top while moving Tab Bar just like on Vivaldi. There was also problem that after enabling menu, titlebar buttons were duplicated, now fixed.

### CODE REVIEW

**Comment by hawkeye116477** [comment]
@MrAlex94 Are you tested that and had any problems?

**Comment by hawkeye116477** [comment]
Additional new changes:
* added possibility to set Window Controls position
* added possibility to set Waterfox Current logo as menu icon 
* added possibility to set Bookmarks Toolbar position
* little changed all-new settings layout (added columned settings, etc.)
* moved WebRTC and HTTP Referrer Header to better place

**Comment by laniakea64** [comment]
Something in this pull request has resulted in tabs not filling up the whole width of the tab bar, leaving empty space on the end.  Setting "Window Controls Position" to "Left side" moves this empty space to the left of all the open tabs.

**Comment by MrAlex94** [comment]
Thanks for the report. Will see what I can reproduce.

**Pull request merged**
