### PR TITLE
[Classic] Enable new regexp engine

### LINKED ISSUE #2204: [classic] Linkedin has no menu
image

anyone has the same problem? also tried to enable polly.

```
21:05:58.150 Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively. (unknown)
21:05:58.150 Content Security Policy: Couldn’t parse invalid host 'report-sample'  (unknown)
21:05:58.150 Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified  (unknown)
21:05:59.111 Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src 'sha256-6gLjSWp3GRKZCUFvRX5aGHtECD1wVRgJOJp7r0ZQjV0=' 'unsafe-inline' https://s.c.lnkd.licdn.com https://static-fstl.licdn.com https://static-src.linkedin.com https://www.linkedin.com/voyager/service-worker-push.js https://static-lcdn.licdn.com https://s.c.lcdn.licdn.com https://www.linkedin.com/sc/ https://www.linkedin.com/scds/ https://qprod.www.linkedin.com/sc/ https://www.linkedin.com/sw.js https://www.linkedin.com/voyager/abp-detection.js https://snap.licdn.com/li.lms-analytics/ https://platform.linkedin.com/js/analytics.js https://platform-akam.linkedin.com/js/analytics.js https://platform-ecst.linkedin.com/js/analytics.js https://platform-azur.linkedin.com/js/analytics.js https://platform.linkedin.com/litms/utag/ https://platform-akam.linkedin.com/litms/utag/ https://platform-ecst.linkedin.com/litms/utag/ https://platform-azur.linkedin.com/litms/utag/ https://platform.linkedin.com/litms/vendor/ https://platform-akam.linkedin.com/litms/vendor/ https://platform-ecst.linkedin.com/litms/vendor/ https://platform-azur.linkedin.com/litms/vendor/ https://static.licdn.com https://static-exp1.licdn.com https://static-exp2.licdn.com https://static-exp3.licdn.com”). Source: (function(){var e={exports:{}};e.exports....  feed:1
21:06:03.505 unreachable code after return statement[Learn More]  71m5uc1gfdc7t2dngntel8r4v:6537
21:06:04.004 unreachable code after return statement[Learn More]  8dgb5qbqlkhuculo3fn9grybr:6
21:06:12.030 Terminator datalet is not seen within 12000 ms.  9lm1w74nbjr3k3lavicf1gdym:63:348
21:06:15.844 unreachable code after return statement[Learn More]  8dgb5qbqlkhuculo3fn9grybr:6
21:06:17.546 Using profile voyager-web-feed for route feed.index.index  6oydvamu0ccyz6bjubzwr4zq1:58:226
21:06:18.670 SyntaxError: invalid regexp group  71m5uc1gfdc7t2dngntel8r4v:34469:187
21:06:22.271 Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive. (unknown)
21:06:23.120 Loading failed for the <script> with source “https://platform.linkedin.com/litms/utag/voyager-web-feed/utag.js?cb=1628535900000”.  feed:1
21:06:24.740 XML Parsing Error: no root element found
Location: https://realtime.www.linkedin.com/realtime/realtimeFrontendClientConnectivityTracking?action=sendHeartbeat
Line Number 1, Column 1:  realtimeFrontendClientConnectivityTracking:1:1
21:06:26.278 This response was unable to be parsed as json.   71m5uc1gfdc7t2dngntel8r4v:17301:44
21:06:28.696 This response was unable to be parsed as json.   71m5uc1gfdc7t2dngntel8r4v:17301:44
21:06:29.943 This response was unable to be parsed as json.   71m5uc1gfdc7t2dngntel8r4v:17301:44
21:06:32.379 This response was unable to be parsed as json.   71m5uc1gfdc7t2dngntel8r4v:17301:44
21:06:32.736 This response was unable to be parsed as json.   71m5uc1gfdc7t2dngntel8r4v:17301:44
21:06:33.429 This response was unable to be parsed as json.   71m5uc1gfdc7t2dngntel8r4v:17301:44
21:06:34.404 This response was unable to be parsed as json.   71m5uc1gfdc7t2dngntel8r4v:17301:44
21:06:35.589 This response was unable to be parsed as json.   71m5uc1gfdc7t2dngntel8r4v:17301:44
```

why isn't it possible anymore to add bugs for classic? isn't classic **the** reason to go for waterfox (support of the good addons)? will you let classic die? maybe the feature request is "please keep developing waterfox classic"

### PR DESCRIPTION
**Pull request by hawkeye116477**
Just like Mozilla wrote:

The [RegExp](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) engine [has been updated](https://hacks.mozilla.org/2020/06/a-new-regexp-engine-in-spidermonkey/) and now supports all new features introduced in ECMAScript 2018: 
* [Lookbehind assertions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Assertions)
* [Unicode property escapes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes)
* [Named capture groups](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Groups_and_Ranges)

They say also about `RegExp.prototype.dotAll`, but we had that even before that.

-----------------

What left to do:
* ~Changing requirements of compilers versions~
* ~Testing on Windows~
* ~Testing on Linux~
* Testing on macOS (I don't have it, so someone other will need to check that, ~but at least I will see if all builds well on GH Actions~)
* Removing old regexp engine
* Maybe updating regexp engine to match version which is in latest 91 ESR

However I think that 2 last things I'll do maybe after 2021.09 version.

PS: I skipped BinJS hookups, because WF Classic don't have a Binary AST parser in engine.

This fixes #2204 and #2152.

PR also contains enabling C++17 mode, which is needed for new regexp code.
It also raises minimum required Clang/LLVM version to 6.0 and GCC to 7.1.

I also needed to fix problems with compiling after enabling C++17 mode and some of the problems Mozilla solved by removing `using namespace std`, but because WF Classic has a lot of that in code, I did that partially also by different method => [de-unifying](https://repo.palemoon.org/MoonchildProductions/UXP/issues/80).

### CODE REVIEW

**Comment by hawkeye116477** [comment]
Looks like that it builds fine on Linux and Mac, but there are some issues on Windows. Mozilla chose removing "using namespace std", but seems that on Classic it's on many files, so I'l do that partially also by other method - de-unifying. 
I'm expecting that probably now on macOS build will fail now, but I don't need approval for now, I'll just rerun GH Actons build from my forked repo.

**Comment by hawkeye116477** [comment]
I solved all issues now. Here is Windows build for testing: https://github.com/hawkeye116477/Waterfox/releases/tag/new_regexp
and for Linux and Mac => https://github.com/WaterfoxCo/Waterfox/actions/runs/1194741791.
@reallyuniquename @c33s @EternityEngine @sutex

**Comment by c33s** [comment]
@hawkeye116477 thank you very very much for your effort. i should be able to test the build on monday.

**Comment by c33s** [comment]
@hawkeye116477 did a short test on gitlab. looks good to me. will try to do more tests with it this week

**Comment by reallyuniquename** [comment]
Thanks for the improvements @hawkeye116477, it seems to work well.

**Comment by hawkeye116477** [comment]
I added additional fixes for compiling with C++17 mode, because I tested on clang packages from official CentOS repo and were problems.
I also raised the minimum Clang version to 6, because otherwise Clang complains about webrtc code (it's a bug in Clang => https://lists.llvm.org/pipermail/cfe-dev/2017-August/055249.html). Maybe that could be somehow workarounded, but I checked on https://pkgs.org/ which version of Clang is on all currently supported distros and seems that all have Clang 6 or higher, so it's rather not worth to do.

**Comment by reallyuniquename** [comment]
@MrAlex94 is there ETA on when this hits release builds?

**Pull request merged**
