### PR TITLE
Update bootstraploader

### LINKED ISSUE #2264: Please update bootstrap loader for legacy extension to newerst version
The bootstrap loader have under go many updates. Waterfox should just catch on. This fall behind already cause some extension can't be update to its newest version.

### PR DESCRIPTION
**Pull request by 117649**
#2321
#2264

### CODE REVIEW

**Comment by MrAlex94** [comment]
Curious: has this been tested? Did you find bootstrapped addons working correctly?

**Comment by 117649** [comment]
> 
> 
> Curious: has this been tested? Did you find bootstrapped addons working correctly?

@MrAlex94 
Yes, Definitely. I've tested by directly edit omni.ja with 7-zip.
图片

**Comment by MrAlex94** [comment]
Interesting. I will fix the changes mentioned above and test as well.

**Comment by MrAlex94** [comment]
I've been testing this and it seems to still return add-ons as corrupt. Will find a fix in the coming days.

**Comment by 117649** [comment]
> 
> 
> I've been testing this and it seems to still return add-ons as corrupt. Will find a fix in the coming days.

@MrAlex94 Can you post a detailed error message?
This just weird.

**Comment by MrAlex94** [comment]
> > I've been testing this and it seems to still return add-ons as corrupt. Will find a fix in the coming days.
> 
> @MrAlex94 Can you post a detailed error message? This just weird.

Sure:
```
1635170578580	addons.xpi	WARN	Invalid XPI: Error: File /Users/akontos/Downloads/linkstatusredux.xpi does not contain a valid manifest(resource://gre/modules/addons/XPIInstall.jsm:669:11) JS Stack trace: loadManifest@XPIInstall.jsm:669:11
openLinkIn@utilityOverlay.js:706:19
openUILinkIn@utilityOverlay.js:352:13
openTrustedLinkIn@utilityOverlay.js:269:15
fpCallback_done@browser.js:2959:26
```

Currently working on other issues - but will jump in where I can regarding this bug.

**Comment by 117649** [comment]
@MrAlex94 
图片
Just tested on G4.0.1 no problem install here.

**Comment by MrAlex94** [comment]
Is that from building or from editing `omni.ja`?

**Comment by 117649** [comment]
Editing. It just too much for me to setup a build chain.
I don't know if there is multiple files of same name in this repo but it should work if those made into `omni.ja`s were changed according to this pr.

**Comment by MrAlex94** [comment]
Thanks for making the first steps - when we've ironed out some more issues we'll come back to this and figure out what's wrong. I don't think it will be too complex.

**Comment by MrAlex94** [comment]
Finally have it working!
image

Will close this and push directly into `current` branch.

**Pull request closed without merging**
