### PR TITLE
v68: Fix bookmark star button

### PR DESCRIPTION
**Pull request by laniakea64**
Fixes https://github.com/MrAlex94/Waterfox/issues/950

### CODE REVIEW

**Comment by grahamperrin** [comment]
@laniakea64 thanks, would you like to roll any other bookmark-related fixes into this PR? Or treat each set of symptoms as discrete? 

At a glance: 

- <strike>`https://www.reddit.com/comments/bnzr6p/-/enx7wcl/?context=2` possibly impacted by import/migration</strike>
- https://www.reddit.com/comments/bpfa6u/-/eo679j0/ not involving import/migration (I can't tell whether the same is true for the OP there)
- …

**Comment by laniakea64** [comment]
The issue with Ctrl-D is already fixed by this PR.

Reading the full context of the import issue, that one is about Waterfox 56.2.9, so it's totally unrelated to this.

**Comment by MrAlex94** [comment]
Will take a look at this :-)

**Comment by grahamperrin** [comment]
> … context of the import issue, that one is about Waterfox 56.2.9 …

My bad! Sorry. Thanks @laniakea64 for pointing out my mistake.

**Pull request merged**
