### PR TITLE
[Classic] Fix YT 360 videos crashing on Windows.

### PR DESCRIPTION
**Pull request by hawkeye116477**
https://github.com/MrAlex94/Waterfox/issues/1588

### CODE REVIEW

**Comment by Squall-Leonhart** [comment]
I don't have crashing with these videos in the first place, I suggest alternatively finding the real cause and not just indiscriminately reverting things from 2017 as this seems excessive for an issue that doesn't appear to exist for all cases.

From what it seems like, its faulting on MSE itself

Edit:
Crash is due d3d11 dxva support on windows 8/10 and the code not handling NPOT NV12

toggling media.windows-media-foundation.allow-d3d11-dxva restores the videos to functioning, the issue doesn't occur on 7 at all.

**Comment by Squall-Leonhart** [comment]
This is most likely the same issue

https://bugzilla.mozilla.org/show_bug.cgi?id=1418831

D3D11 video also suffers from being converted to BGRA 8888
https://bugzilla.mozilla.org/show_bug.cgi?id=1543336

And many fixes for GLBlit video here
https://bugzilla.mozilla.org/show_bug.cgi?id=1540581

**Comment by JohnEdwa** [comment]
>toggling media.windows-media-foundation.allow-d3d11-dxva restores the videos to functioning, the issue doesn't occur on 7 at all.

Interestingly it fixes it on a clean profile, but for some reason not on my normal one.

**Comment by Squall-Leonhart** [comment]
> 
> 
> > toggling media.windows-media-foundation.allow-d3d11-dxva restores the videos to functioning, the issue doesn't occur on 7 at all.
> 
> Interestingly it fixes it on a clean profile, but for some reason not on my normal one.

is h264ify enabled in your usual profile?

**Comment by hawkeye116477** [comment]
`Interestingly it fixes it on a clean profile, but for some reason not on my normal one.`

For me that doesn't help, only advertisement appears, then I skip it and then tab crashes.

**Comment by JohnEdwa** [comment]
@Squall-Leonhart 
> is h264ify enabled in your usual profile?

Seems that it wasn't, installing https://addons.mozilla.org/en-US/firefox/addon/h264ify/ and setting that about config flag fixes the 360 videos.

**Pull request merged**
