### PR TITLE
[WFX-375] Remove blank space before private tab menuitems.

### PR DESCRIPTION
**Pull request by adamp01**
This is primarily to remove the indentation before private tab menuitem's in context menu's. This will be most notable on Firefox default themes on Windows. It will also no longer add a check mark to the tab context menu "Private Tab" menuitem.  Instead it will change the wording from "Make Private Tab" to "End Private Mode" depending on the current tabs usercontextid (container). Really need to think about the wording though.

Check mark pushes all items to the side:
image

`menuitem-iconic` class creates additional space on Windows:
image

### CODE REVIEW

**Comment by MrAlex94** [comment]
@adamp01, sorry had to rebase for the fixes yesterday.

**Review by davidmaxwaterman — APPROVED** [review]
lgtm

**Comment by adamp01** [comment]
Need to update Lepton once https://github.com/black7375/Firefox-UI-Fix/pull/357 merged.

**Comment by adamp01** [comment]
Wording updated to "Make Private Tab", "Exit Private Tab"

**Comment by adamp01** [comment]
@davidmaxwaterman - should be good to merge

**Review by MrAlex94 — APPROVED** [review]

**Pull request merged**
