### PR TITLE
"Help" buttons shall lead to Waterfox's reddit page -> #548

### PR DESCRIPTION
**Pull request by ghost**
As proposed in #548 this PR changes the "Help" footer at the bottom of the settings, the "Waterfox Help" button in the hamburger menu and in the menu bar. They'll now lead to Waterfox's reddit page instead of Mozilla's help website.

### CODE REVIEW

**Comment by criztovyl** [comment]
Wouldn't it be better to change the underlying links instead of hard-coding Reddit?

While this won't work directly I would suggest to point the links to a new subdomain support.waterfoxproject.org, which then simply redirects everything to Reddit.

**Comment by criztovyl** [comment]
i.e. change `app.support.baseURL` pref from `https://support.mozilla.org/1/firefox/%VERSION%/%OS%/%LOCALE%/` to `https://support.waterfoxproject.org/1/waterfox/%VERSION%/%OS%/%LOCALE%/` and then using server-side rewrites on `support.waterfoxproject.org/*` to redirect all the request (temporarily?) to `https://reddit.com/r/waterfox`.

**Comment by criztovyl** [comment]
Just my thoughts. :)

**Comment by ghost** [comment]
@criztovyl 

I also thought about this. But changing _app.support.baseURL_ would also break all the other help entries. And some of them still hold useful information like "Keyboard Shortcuts".

**Comment by criztovyl** [comment]
Didn't think about that. ^^
I shortly thought about maybe forking the help infrastructure, but I think that's absolutely not the way to go (neither did I find the help data nor is it feasible to maintain that additional infrastructure).

So, just ignore my comments ^^

**Comment by PandaCodex** [comment]
In Cyberfox `app.support.baseURL`  points to there forums and forum documents. They coded in 
```javascript
pref("app.helpdoc.baseURI", "https://support.mozilla.org/1/Firefox/%VERSION%/%OS%/%LOCALE%/");
``` 
which sends users to Mozilla help documents. Could port these changes over to Waterfox so basic `app.support.baseURL`  points to Reddit where all others point to Mozilla threads for the time being until Alex mirrors there help system or implements own. 

Would this be a PR wanted???

**Comment by ghost** [comment]
@PandaCodex

 I think that'd be a better solution than hard-coding our Reddit URL! :)

**Comment by grahamperrin** [comment]
> … suggest to point the links to a new subdomain support.waterfoxproject.org, which then simply redirects everything to Reddit. …

Meta/tracking: #582

**Comment by grahamperrin** [comment]
Meta, tracking: #538

Maybe expand this PR to cover other areas that should refer to the subreddit? 

### about:support (troubleshooting information)

> … support web site.  …

- refers to https://support.mozilla.org/1/firefox/56.2.14/FreeBSD/en-GB/ (on FreeBSD), redirects to https://support.mozilla.org/en-US/products/firefox?as=u&utm_source=inproduct
- should refer to https://www.reddit.com/r/waterfox/

**Pull request closed without merging**
