### PR TITLE
Unbreak page reload on Twitter with uBlock Origin when e10s is disabled

### LINKED ISSUE #580: AdNauseam, Findx Privacy Control, Ghostery, HTTPS Everywhere, Nano Adblocker, Privacy Badger and uBlock Origin are bugged by single-process Waterfox
## Observations, steps

Single-process. With any of these enabled:

- [Findx Privacy Control](https://addons.mozilla.org/addon/findx-privacy-control/) 1.15.5.4
- [Privacy Badger](https://addons.mozilla.org/addon/privacy-badger17/) 2018.5.10 
- [uBlock Origin](https://addons.mozilla.org/addon/ublock-origin/) 1.16.6

– some types of navigation, from one URL to another, are bugged. 

Most noticeable with Twitter, for example: 

1. go to https://twitter.com/freebsd
2. overtype _freebsd_ with _waterfoxproject_
3. <kbd>→</kbd>
4. <kbd>Return</kbd> or <kbd>Enter</kbd>

### Expected

- https://twitter.com/waterfoxproject page content; **and**
- the page title –

> Waterfox Web Browser (@Waterfoxproject) | Twitter

– in the title bar (if a title is allowed there); in the tab; and in (e.g.) the Task Manager of KDE

### Actual result

- https://twitter.com/freebsd page content
- no title in the title bar 
- `twitter.com/waterfoxproject` in the tab
- no title in Task Manager

2018-05-23 22 48 29 waterfox

## Workaround

5. <kbd>Control</kbd>-<kbd>L</kbd> then <kbd>Return</kbd> or <kbd>Enter</kbd>

– or reload. 

## Thoughts

For around a week (beginning ~2018-05-16) I _imagined_ that the issue arose around the time of testing then releasing Waterfox 56.2.0. This evening I proved myself wrong by quickly reproducing the issue with 56.1.0. 

It's possible that all three extensions share the same bugged code, however this issue does feel regressive to me. 

## Not comparably bugged

[Disconnect](https://addons.mozilla.org/addon/disconnect/) 5.18.21

[Malwarebytes Browser Extension BETA](https://addons.mozilla.org/addon/malwarebytes/) 1.0.21

### PR DESCRIPTION
**Pull request by jbeich**
Fixes #580

### CODE REVIEW

**Comment by grahamperrin** [comment]
Thanks :+1: 

Building www/waterfox 56.2.0.53 now, https://svnweb.freebsd.org/ports?view=revision&revision=472399

Nit: 

> Unbreak page reload on Twitter …

AFAIK the breakage is around _load_, with reload as a workaround. (TBH I didn't test extensively with Twitter, the https://www.logilab.org/ case is more easily reproducible with a single click.)

**Comment by grahamperrin** [comment]
Single-process [www/waterfox](https://www.freshports.org/www/waterfox) on FreeBSD-CURRENT is now good for the **Twitter** and **Logilab.org** test cases with: 

- Findx Privacy Control
- Ghostery
- Nano Adblocker
- Privacy Badger
- uBlock Origin. 

```text
$ pkg info waterfox | grep Version
Version        : 56.2.0.53
$ date ; uname -v
Fri 15 Jun 2018 04:41:48 BST
FreeBSD 12.0-CURRENT #5 r335024: Wed Jun 13 11:04:24 BST 2018     root@momh167-gjp4-hpelitebook8570p-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC 
```

**Comment by grahamperrin** [comment]
https://github.com/gorhill/uBlock/wiki/Firefox-WebExtensions#read-carefully-if-using-ubowebext refers to to Mozilla bug [1348497 - Ebay embedded Paypal Checkout fails to load (spins forever) with NoScript and e10s DISABLED](https://bugzilla.mozilla.org/show_bug.cgi?id=1348497) … 

… I don't plan to test eBay or PayPal.

@gorhill please, would you like to suggest any other test case before I confirm this pull request as a fix for #580?

**Comment by MrAlex94** [comment]
Just so I have future reference, this is [Bug 1396395](https://bugzilla.mozilla.org/show_bug.cgi?id=1396395).

**Pull request merged**
