### PR TITLE
[Current] Bug 554279 - Defer toolbar initialization...

### PR DESCRIPTION
**Pull request by hawkeye116477**
Looks like that helps for #1686 and #1683 but maybe it will need additional testing.

### CODE REVIEW

**Comment by Peacock365** [comment]
Semi-OT: If the bookmarks toolbar position is set to "bottom" in the settings, the option to hide the bookmarks toolbar under _View --> Toolbars_ vanishes / is no longer visible. Waterfox Current 2020.07.1.

**Comment by hawkeye116477** [comment]
@Peacock365 I don't what you mean by Semi-OT. Anyway it's different issue, not related with that.

**Comment by Peacock365** [comment]
@hawkeye116477 

Could you take a look at it regardless? This bothers me a lot.

**Comment by InvisibleManX** [comment]
@hawkeye116477 after some searching I see it's just another slang "semi off-topic"...

**Comment by InvisibleManX** [comment]
@Peacock365 how do you even set the bookmarks toolbar to be shown in the bottom? I can only make it visible in the top.

**Comment by Peacock365** [comment]
@InvisibleManX 

Go to _about:preferences#general_, there is an option for that.

**Pull request merged**
