### PR TITLE
[G3] Additional modularisation

### PR DESCRIPTION
**Pull request by adamp01**

### CODE REVIEW

**Review by MrAlex94 — COMMENTED** [review]
All good - although usage of fluent is preferred due to DTD's deprecation in the code base.
https://firefox-source-docs.mozilla.org/l10n/fluent/tutorial.html#registering-new-l10n-files

**Comment by UInt2048** [comment]
Seems like this PR was reverted.

**Comment by UInt2048** [comment]
It seems like this PR was reverted. What happened? I don't see anything on the site or in release notes, etc. that explains...

**Comment by MrAlex94** [comment]
> It seems like this PR was reverted. What happened? I don't see anything on the site or in release notes, etc. that explains...

It was causing `about:preferences` to not load properly, depending on how you accessed the page.

**Pull request merged**
