### PR TITLE
[Classic] Update ffvpx to 4.0.2 and fix displaying of VP9 profiles 1, 2 and 3 

### PR DESCRIPTION
**Pull request by hawkeye116477**
Related:
https://bugzilla.mozilla.org/show_bug.cgi?id=1488065
https://bugzilla.mozilla.org/show_bug.cgi?id=1215089

### CODE REVIEW

**Comment by hawkeye116477** [comment]
Seems that something went bad and 2 last PR's aren't on classic branch.

**Comment by MrAlex94** [comment]
Should be there now!

**Comment by MrAlex94** [comment]
I think this pull might have broken YouTube playback on Windows. My fault for not testing properly on all platforms. I've noticed some Windows specific paths not updated, will see if that resolved things.

**Comment by hawkeye116477** [comment]
@MrAlex94 I tested on Windows now and seems that's not that PR, but https://github.com/MrAlex94/Waterfox/pull/1180, seems that I updated to too new commit (probably something another special needs to be added for Windows) and downgrading it to the same commit which was used in Current fixes YouTube playback on Windows. Anyway, sorry for problems.

**Pull request merged**
