### PR TITLE
Refactor: Remove Google Analytics on about:addons

### PR DESCRIPTION
**Pull request by PandaCodex**
Cleaner implementation of this, apparently don't need to loop reg or unreg. Single add-remove was good enough.

### CODE REVIEW

**Comment by PandaCodex** [comment]
@MrAlex94 are you going to use this cleaner implementation

**Comment by MrAlex94** [comment]
I've been busy getting v55 and its updates ready, but once this next release is out will look through it.

**Comment by PandaCodex** [comment]
Will this be included in 56 release @MrAlex94

**Comment by MrAlex94** [comment]
https://github.com/MrAlex94/Waterfox/commit/394096b8a96f8ccc7610ce313c5a5bffd4c682db

**Pull request closed without merging**
